// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: entries.sql

package database

import (
	"context"
	"database/sql"

	"github.com/feed-me/types"
)

const editDomainEntryById = `-- name: EditDomainEntryById :execresult
UPDATE domain_entries SET comment = ?, valid_until = ? WHERE id = ?
`

func (q *Queries) EditDomainEntryById(ctx context.Context, comment sql.NullString, validUntil sql.NullTime, iD int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, editDomainEntryById, comment, validUntil, iD)
}

const editIPEntryById = `-- name: EditIPEntryById :execresult
UPDATE ip_entries SET comment = ?, valid_until = ? WHERE id = ?
`

func (q *Queries) EditIPEntryById(ctx context.Context, comment sql.NullString, validUntil sql.NullTime, iD int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, editIPEntryById, comment, validUntil, iD)
}

const editURLEntryById = `-- name: EditURLEntryById :execresult
UPDATE url_entries SET comment = ?, valid_until = ? WHERE id = ?
`

func (q *Queries) EditURLEntryById(ctx context.Context, comment sql.NullString, validUntil sql.NullTime, iD int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, editURLEntryById, comment, validUntil, iD)
}

const getDomainEnabledEntries = `-- name: GetDomainEnabledEntries :many
SELECT value FROM domain_entries WHERE enabled = ? AND feed_id = ? AND (valid_until IS NULL OR valid_until >= ?)
`

func (q *Queries) GetDomainEnabledEntries(ctx context.Context, enabled bool, feedID int32, validUntil sql.NullTime) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDomainEnabledEntries, enabled, feedID, validUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var value string
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIPEnabledEntries = `-- name: GetIPEnabledEntries :many
SELECT value FROM ip_entries WHERE enabled = ? AND feed_id = ? AND (valid_until IS NULL OR valid_until >= ?)
`

func (q *Queries) GetIPEnabledEntries(ctx context.Context, enabled bool, feedID int32, validUntil sql.NullTime) ([]types.MyNet, error) {
	rows, err := q.db.QueryContext(ctx, getIPEnabledEntries, enabled, feedID, validUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []types.MyNet
	for rows.Next() {
		var value types.MyNet
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getURLEnabledEntries = `-- name: GetURLEnabledEntries :many
SELECT value FROM url_entries WHERE enabled = ? AND feed_id = ? AND (valid_until IS NULL OR valid_until >= ?)
`

func (q *Queries) GetURLEnabledEntries(ctx context.Context, enabled bool, feedID int32, validUntil sql.NullTime) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getURLEnabledEntries, enabled, feedID, validUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var value string
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDomainEntry = `-- name: InsertDomainEntry :execresult
INSERT INTO domain_entries (value, comment, valid_until, feed_id) VALUES (?, ?, ?, ?)
`

func (q *Queries) InsertDomainEntry(ctx context.Context, value string, comment sql.NullString, validUntil sql.NullTime, feedID int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertDomainEntry,
		value,
		comment,
		validUntil,
		feedID,
	)
}

const insertIPEntry = `-- name: InsertIPEntry :execresult
INSERT INTO ip_entries (value, comment, valid_until, feed_id) VALUES (?, ?, ?, ?)
`

func (q *Queries) InsertIPEntry(ctx context.Context, value types.MyNet, comment sql.NullString, validUntil sql.NullTime, feedID int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertIPEntry,
		value,
		comment,
		validUntil,
		feedID,
	)
}

const insertURLEntry = `-- name: InsertURLEntry :execresult
INSERT INTO url_entries (value, comment, valid_until, feed_id) VALUES (?, ?, ?, ?)
`

func (q *Queries) InsertURLEntry(ctx context.Context, value string, comment sql.NullString, validUntil sql.NullTime, feedID int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertURLEntry,
		value,
		comment,
		validUntil,
		feedID,
	)
}

const listDomainEntries = `-- name: ListDomainEntries :many

SELECT id, value, enabled, comment, valid_until, feed_id FROM domain_entries WHERE feed_id = ?
`

// --------------------
//
//	DOMAIN ENTRIES
//
// --------------------
func (q *Queries) ListDomainEntries(ctx context.Context, feedID int32) ([]DomainEntry, error) {
	rows, err := q.db.QueryContext(ctx, listDomainEntries, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DomainEntry
	for rows.Next() {
		var i DomainEntry
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Enabled,
			&i.Comment,
			&i.ValidUntil,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainEntriesWindow = `-- name: ListDomainEntriesWindow :many
SELECT id, value, enabled, comment, valid_until, feed_id FROM domain_entries WHERE feed_id = ? LIMIT ? OFFSET ?
`

func (q *Queries) ListDomainEntriesWindow(ctx context.Context, feedID int32, limit int32, offset int32) ([]DomainEntry, error) {
	rows, err := q.db.QueryContext(ctx, listDomainEntriesWindow, feedID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DomainEntry
	for rows.Next() {
		var i DomainEntry
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Enabled,
			&i.Comment,
			&i.ValidUntil,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIPEntries = `-- name: ListIPEntries :many

SELECT id, value, enabled, comment, valid_until, feed_id FROM ip_entries WHERE feed_id = ?
`

// ----------------
//
//	IP ENTRIES
//
// ----------------
func (q *Queries) ListIPEntries(ctx context.Context, feedID int32) ([]IpEntry, error) {
	rows, err := q.db.QueryContext(ctx, listIPEntries, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IpEntry
	for rows.Next() {
		var i IpEntry
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Enabled,
			&i.Comment,
			&i.ValidUntil,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIPEntriesWindow = `-- name: ListIPEntriesWindow :many
SELECT id, value, enabled, comment, valid_until, feed_id FROM ip_entries WHERE feed_id = ? LIMIT ? OFFSET ?
`

func (q *Queries) ListIPEntriesWindow(ctx context.Context, feedID int32, limit int32, offset int32) ([]IpEntry, error) {
	rows, err := q.db.QueryContext(ctx, listIPEntriesWindow, feedID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IpEntry
	for rows.Next() {
		var i IpEntry
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Enabled,
			&i.Comment,
			&i.ValidUntil,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listURLEntries = `-- name: ListURLEntries :many

SELECT id, value, enabled, comment, valid_until, feed_id FROM url_entries WHERE feed_id = ?
`

// -----------------
//
//	URL ENTRIES
//
// -----------------
func (q *Queries) ListURLEntries(ctx context.Context, feedID int32) ([]UrlEntry, error) {
	rows, err := q.db.QueryContext(ctx, listURLEntries, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UrlEntry
	for rows.Next() {
		var i UrlEntry
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Enabled,
			&i.Comment,
			&i.ValidUntil,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listURLEntriesWindow = `-- name: ListURLEntriesWindow :many
SELECT id, value, enabled, comment, valid_until, feed_id FROM url_entries WHERE feed_id = ? LIMIT ? OFFSET ?
`

func (q *Queries) ListURLEntriesWindow(ctx context.Context, feedID int32, limit int32, offset int32) ([]UrlEntry, error) {
	rows, err := q.db.QueryContext(ctx, listURLEntriesWindow, feedID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UrlEntry
	for rows.Next() {
		var i UrlEntry
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Enabled,
			&i.Comment,
			&i.ValidUntil,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDomainEntry = `-- name: RemoveDomainEntry :execresult
DELETE FROM domain_entries WHERE id = ?
`

func (q *Queries) RemoveDomainEntry(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeDomainEntry, id)
}

const removeIPEntry = `-- name: RemoveIPEntry :execresult
DELETE FROM ip_entries WHERE id = ?
`

func (q *Queries) RemoveIPEntry(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeIPEntry, id)
}

const removeURLEntry = `-- name: RemoveURLEntry :execresult
DELETE FROM url_entries WHERE id = ?
`

func (q *Queries) RemoveURLEntry(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeURLEntry, id)
}
