// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: entries.sql

package database

import (
	"context"

	"github.com/feed-me/types"
	"github.com/jackc/pgx/v5/pgtype"
)

const editDomainEntryById = `-- name: EditDomainEntryById :exec
UPDATE domain_entries SET enabled = $1, description = $2, valid_until = $3 WHERE id = $4 RETURNING id, value, enabled, description, valid_until, feed_id
`

func (q *Queries) EditDomainEntryById(ctx context.Context, enabled bool, description *string, validUntil pgtype.Timestamp, iD int64) error {
	_, err := q.db.Exec(ctx, editDomainEntryById,
		enabled,
		description,
		validUntil,
		iD,
	)
	return err
}

const editIPEntryById = `-- name: EditIPEntryById :exec
UPDATE ip_entries SET enabled = $1, description = $2, valid_until = $3 WHERE id = $4 RETURNING id, value, enabled, description, valid_until, feed_id
`

func (q *Queries) EditIPEntryById(ctx context.Context, enabled bool, description *string, validUntil pgtype.Timestamp, iD int64) error {
	_, err := q.db.Exec(ctx, editIPEntryById,
		enabled,
		description,
		validUntil,
		iD,
	)
	return err
}

const editURLEntryById = `-- name: EditURLEntryById :exec
UPDATE url_entries SET enabled = $1, description = $2, valid_until = $3 WHERE id = $4 RETURNING id, value, enabled, description, valid_until, feed_id
`

func (q *Queries) EditURLEntryById(ctx context.Context, enabled bool, description *string, validUntil pgtype.Timestamp, iD int64) error {
	_, err := q.db.Exec(ctx, editURLEntryById,
		enabled,
		description,
		validUntil,
		iD,
	)
	return err
}

const getDomainEnabledEntries = `-- name: GetDomainEnabledEntries :many
SELECT value FROM domain_entries WHERE enabled = TRUE AND feed_id = $1 AND (valid_until IS NULL OR valid_until >=$2)
`

func (q *Queries) GetDomainEnabledEntries(ctx context.Context, feedID int64, validUntil pgtype.Timestamp) ([]string, error) {
	rows, err := q.db.Query(ctx, getDomainEnabledEntries, feedID, validUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var value string
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDomainEntryById = `-- name: GetDomainEntryById :one
SELECT id, value, enabled, description, valid_until, feed_id FROM domain_entries WHERE id = $1 AND feed_id = $2
`

func (q *Queries) GetDomainEntryById(ctx context.Context, iD int64, feedID int64) (DomainEntry, error) {
	row := q.db.QueryRow(ctx, getDomainEntryById, iD, feedID)
	var i DomainEntry
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.Enabled,
		&i.Description,
		&i.ValidUntil,
		&i.FeedID,
	)
	return i, err
}

const getIPEnabledEntries = `-- name: GetIPEnabledEntries :many
SELECT value FROM ip_entries WHERE enabled = TRUE AND feed_id = $1 AND (valid_until IS NULL OR valid_until >= $2)
`

func (q *Queries) GetIPEnabledEntries(ctx context.Context, feedID int64, validUntil pgtype.Timestamp) ([]types.MyNet, error) {
	rows, err := q.db.Query(ctx, getIPEnabledEntries, feedID, validUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []types.MyNet{}
	for rows.Next() {
		var value types.MyNet
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIPEntryById = `-- name: GetIPEntryById :one
SELECT id, value, enabled, description, valid_until, feed_id FROM ip_entries WHERE id = $1 AND feed_id = $2
`

func (q *Queries) GetIPEntryById(ctx context.Context, iD int64, feedID int64) (IpEntry, error) {
	row := q.db.QueryRow(ctx, getIPEntryById, iD, feedID)
	var i IpEntry
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.Enabled,
		&i.Description,
		&i.ValidUntil,
		&i.FeedID,
	)
	return i, err
}

const getURLEnabledEntries = `-- name: GetURLEnabledEntries :many
SELECT value FROM url_entries WHERE enabled = TRUE AND feed_id = $1 AND (valid_until IS NULL OR valid_until >= $2)
`

func (q *Queries) GetURLEnabledEntries(ctx context.Context, feedID int64, validUntil pgtype.Timestamp) ([]string, error) {
	rows, err := q.db.Query(ctx, getURLEnabledEntries, feedID, validUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var value string
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getURLEntryById = `-- name: GetURLEntryById :one
SELECT id, value, enabled, description, valid_until, feed_id FROM url_entries WHERE id = $1 AND feed_id = $2
`

func (q *Queries) GetURLEntryById(ctx context.Context, iD int64, feedID int64) (UrlEntry, error) {
	row := q.db.QueryRow(ctx, getURLEntryById, iD, feedID)
	var i UrlEntry
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.Enabled,
		&i.Description,
		&i.ValidUntil,
		&i.FeedID,
	)
	return i, err
}

const insertDomainEntry = `-- name: InsertDomainEntry :one
INSERT INTO domain_entries (value, description, valid_until, feed_id) VALUES ($1, $2, $3, $4) RETURNING id, value, enabled, description, valid_until, feed_id
`

func (q *Queries) InsertDomainEntry(ctx context.Context, value string, description *string, validUntil pgtype.Timestamp, feedID int64) (DomainEntry, error) {
	row := q.db.QueryRow(ctx, insertDomainEntry,
		value,
		description,
		validUntil,
		feedID,
	)
	var i DomainEntry
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.Enabled,
		&i.Description,
		&i.ValidUntil,
		&i.FeedID,
	)
	return i, err
}

const insertIPEntry = `-- name: InsertIPEntry :one
INSERT INTO ip_entries (value, description, valid_until, feed_id) VALUES ($1, $2, $3, $4) RETURNING id, value, enabled, description, valid_until, feed_id
`

func (q *Queries) InsertIPEntry(ctx context.Context, value types.MyNet, description *string, validUntil pgtype.Timestamp, feedID int64) (IpEntry, error) {
	row := q.db.QueryRow(ctx, insertIPEntry,
		value,
		description,
		validUntil,
		feedID,
	)
	var i IpEntry
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.Enabled,
		&i.Description,
		&i.ValidUntil,
		&i.FeedID,
	)
	return i, err
}

const insertURLEntry = `-- name: InsertURLEntry :one
INSERT INTO url_entries (value, description, valid_until, feed_id) VALUES ($1, $2, $3, $4) RETURNING id, value, enabled, description, valid_until, feed_id
`

func (q *Queries) InsertURLEntry(ctx context.Context, value string, description *string, validUntil pgtype.Timestamp, feedID int64) (UrlEntry, error) {
	row := q.db.QueryRow(ctx, insertURLEntry,
		value,
		description,
		validUntil,
		feedID,
	)
	var i UrlEntry
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.Enabled,
		&i.Description,
		&i.ValidUntil,
		&i.FeedID,
	)
	return i, err
}

const listDomainEntries = `-- name: ListDomainEntries :many

SELECT id, value, enabled, description, valid_until, feed_id FROM domain_entries WHERE feed_id = $1
`

// --------------------
//
//	DOMAIN ENTRIES
//
// --------------------
func (q *Queries) ListDomainEntries(ctx context.Context, feedID int64) ([]DomainEntry, error) {
	rows, err := q.db.Query(ctx, listDomainEntries, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainEntry{}
	for rows.Next() {
		var i DomainEntry
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Enabled,
			&i.Description,
			&i.ValidUntil,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainEntriesWindow = `-- name: ListDomainEntriesWindow :many
SELECT id, value, enabled, description, valid_until, feed_id FROM domain_entries WHERE feed_id = $1 LIMIT $2 OFFSET $3
`

func (q *Queries) ListDomainEntriesWindow(ctx context.Context, feedID int64, limit int32, offset int32) ([]DomainEntry, error) {
	rows, err := q.db.Query(ctx, listDomainEntriesWindow, feedID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainEntry{}
	for rows.Next() {
		var i DomainEntry
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Enabled,
			&i.Description,
			&i.ValidUntil,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIPEntries = `-- name: ListIPEntries :many

SELECT id, value, enabled, description, valid_until, feed_id FROM ip_entries WHERE feed_id = $1
`

// ----------------
//
//	IP ENTRIES
//
// ----------------
func (q *Queries) ListIPEntries(ctx context.Context, feedID int64) ([]IpEntry, error) {
	rows, err := q.db.Query(ctx, listIPEntries, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IpEntry{}
	for rows.Next() {
		var i IpEntry
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Enabled,
			&i.Description,
			&i.ValidUntil,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIPEntriesWindow = `-- name: ListIPEntriesWindow :many
SELECT id, value, enabled, description, valid_until, feed_id FROM ip_entries WHERE feed_id = $1 LIMIT $2 OFFSET $3
`

func (q *Queries) ListIPEntriesWindow(ctx context.Context, feedID int64, limit int32, offset int32) ([]IpEntry, error) {
	rows, err := q.db.Query(ctx, listIPEntriesWindow, feedID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IpEntry{}
	for rows.Next() {
		var i IpEntry
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Enabled,
			&i.Description,
			&i.ValidUntil,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listURLEntries = `-- name: ListURLEntries :many

SELECT id, value, enabled, description, valid_until, feed_id FROM url_entries WHERE feed_id = $1
`

// -----------------
//
//	URL ENTRIES
//
// -----------------
func (q *Queries) ListURLEntries(ctx context.Context, feedID int64) ([]UrlEntry, error) {
	rows, err := q.db.Query(ctx, listURLEntries, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UrlEntry{}
	for rows.Next() {
		var i UrlEntry
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Enabled,
			&i.Description,
			&i.ValidUntil,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listURLEntriesWindow = `-- name: ListURLEntriesWindow :many
SELECT id, value, enabled, description, valid_until, feed_id FROM url_entries WHERE feed_id = $1 LIMIT $2 OFFSET $3
`

func (q *Queries) ListURLEntriesWindow(ctx context.Context, feedID int64, limit int32, offset int32) ([]UrlEntry, error) {
	rows, err := q.db.Query(ctx, listURLEntriesWindow, feedID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UrlEntry{}
	for rows.Next() {
		var i UrlEntry
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Enabled,
			&i.Description,
			&i.ValidUntil,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDomainEntry = `-- name: RemoveDomainEntry :exec
DELETE FROM domain_entries WHERE id = $1 AND feed_id = $2
`

func (q *Queries) RemoveDomainEntry(ctx context.Context, iD int64, feedID int64) error {
	_, err := q.db.Exec(ctx, removeDomainEntry, iD, feedID)
	return err
}

const removeIPEntry = `-- name: RemoveIPEntry :exec
DELETE FROM ip_entries WHERE id = $1 AND feed_id = $2
`

func (q *Queries) RemoveIPEntry(ctx context.Context, iD int64, feedID int64) error {
	_, err := q.db.Exec(ctx, removeIPEntry, iD, feedID)
	return err
}

const removeURLEntry = `-- name: RemoveURLEntry :exec
DELETE FROM url_entries WHERE id = $1 AND feed_id = $2
`

func (q *Queries) RemoveURLEntry(ctx context.Context, iD int64, feedID int64) error {
	_, err := q.db.Exec(ctx, removeURLEntry, iD, feedID)
	return err
}
