// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feed.sql

package database

import (
	"context"
	"database/sql"
)

const createFeed = `-- name: CreateFeed :execresult
INSERT INTO feeds (name, description, is_public, type) VALUES (?, ?, ?, ?)
`

func (q *Queries) CreateFeed(ctx context.Context, name string, description sql.NullString, isPublic bool, type_ FeedsType) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFeed,
		name,
		description,
		isPublic,
		type_,
	)
}

const editFeedById = `-- name: EditFeedById :exec
UPDATE feeds SET description = ?, is_public = ? WHERE id = ?
`

func (q *Queries) EditFeedById(ctx context.Context, description sql.NullString, isPublic bool, iD int32) error {
	_, err := q.db.ExecContext(ctx, editFeedById, description, isPublic, iD)
	return err
}

const getFeedById = `-- name: GetFeedById :one
SELECT id, name, description, is_public, type FROM feeds WHERE id = ?
`

func (q *Queries) GetFeedById(ctx context.Context, id int32) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedById, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.Type,
	)
	return i, err
}

const getFeedByIdAndType = `-- name: GetFeedByIdAndType :one
SELECT id, name, description, is_public, type FROM feeds WHERE id = ? and type = ?
`

func (q *Queries) GetFeedByIdAndType(ctx context.Context, iD int32, type_ FeedsType) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByIdAndType, iD, type_)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.Type,
	)
	return i, err
}

const getFeedByName = `-- name: GetFeedByName :one
SELECT id, name, description, is_public, type FROM feeds WHERE name = ?
`

func (q *Queries) GetFeedByName(ctx context.Context, name string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByName, name)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.Type,
	)
	return i, err
}

const getFeedTypeById = `-- name: GetFeedTypeById :one
SELECT type FROM feeds WHERE id = ?
`

func (q *Queries) GetFeedTypeById(ctx context.Context, id int32) (FeedsType, error) {
	row := q.db.QueryRowContext(ctx, getFeedTypeById, id)
	var type_ FeedsType
	err := row.Scan(&type_)
	return type_, err
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, name, description, is_public, type FROM feeds
`

func (q *Queries) ListFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFeedById = `-- name: RemoveFeedById :exec
DELETE FROM feeds WHERE id = ?
`

func (q *Queries) RemoveFeedById(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, removeFeedById, id)
	return err
}
