// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feed.sql

package database

import (
	"context"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (name, description, is_public, type) VALUES ($1, $2, $3, $4) RETURNING id, name, description, is_public, type
`

func (q *Queries) CreateFeed(ctx context.Context, name string, description *string, isPublic bool, type_ Feedtype) (Feed, error) {
	row := q.db.QueryRow(ctx, createFeed,
		name,
		description,
		isPublic,
		type_,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.Type,
	)
	return i, err
}

const editFeedById = `-- name: EditFeedById :exec
UPDATE feeds SET description = $1, is_public = $2 WHERE id = $3
`

func (q *Queries) EditFeedById(ctx context.Context, description *string, isPublic bool, iD int64) error {
	_, err := q.db.Exec(ctx, editFeedById, description, isPublic, iD)
	return err
}

const getFeedById = `-- name: GetFeedById :one
SELECT id, name, description, is_public, type FROM feeds WHERE id = $1
`

func (q *Queries) GetFeedById(ctx context.Context, id int64) (Feed, error) {
	row := q.db.QueryRow(ctx, getFeedById, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.Type,
	)
	return i, err
}

const getFeedByIdAndType = `-- name: GetFeedByIdAndType :one
SELECT id, name, description, is_public, type FROM feeds WHERE id = $1 and type = $2
`

func (q *Queries) GetFeedByIdAndType(ctx context.Context, iD int64, type_ Feedtype) (Feed, error) {
	row := q.db.QueryRow(ctx, getFeedByIdAndType, iD, type_)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.Type,
	)
	return i, err
}

const getFeedByName = `-- name: GetFeedByName :one
SELECT id, name, description, is_public, type FROM feeds WHERE name = $1
`

func (q *Queries) GetFeedByName(ctx context.Context, name string) (Feed, error) {
	row := q.db.QueryRow(ctx, getFeedByName, name)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.Type,
	)
	return i, err
}

const getFeedTypeById = `-- name: GetFeedTypeById :one
SELECT type FROM feeds WHERE id = $1
`

func (q *Queries) GetFeedTypeById(ctx context.Context, id int64) (Feedtype, error) {
	row := q.db.QueryRow(ctx, getFeedTypeById, id)
	var type_ Feedtype
	err := row.Scan(&type_)
	return type_, err
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, name, description, is_public, type FROM feeds
`

func (q *Queries) ListFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.Query(ctx, listFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFeedById = `-- name: RemoveFeedById :exec
DELETE FROM feeds WHERE id = $1
`

func (q *Queries) RemoveFeedById(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, removeFeedById, id)
	return err
}
