// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type FeedsType string

const (
	FeedsTypeIp     FeedsType = "ip"
	FeedsTypeDomain FeedsType = "domain"
	FeedsTypeUrl    FeedsType = "url"
)

func (e *FeedsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FeedsType(s)
	case string:
		*e = FeedsType(s)
	default:
		return fmt.Errorf("unsupported scan type for FeedsType: %T", src)
	}
	return nil
}

type NullFeedsType struct {
	FeedsType FeedsType
	Valid     bool // Valid is true if FeedsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFeedsType) Scan(value interface{}) error {
	if value == nil {
		ns.FeedsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FeedsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFeedsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FeedsType), nil
}

type DomainEntry struct {
	ID         int64
	Value      string
	Enabled    bool
	ValidUntil sql.NullTime
	FeedID     int32
}

type Feed struct {
	ID       int32
	Name     string
	IsPublic bool
	Type     FeedsType
}

type Group struct {
	ID   int32
	Name string
}

type GroupPermission struct {
	GroupID      int32
	PermissionID int32
}

type IpEntry struct {
	ID         int64
	Value      []byte
	Mask       uint8
	Enabled    bool
	ValidUntil sql.NullTime
	FeedID     int32
}

type Permission struct {
	ID   int32
	Name string
}

type UrlEntry struct {
	ID         int64
	Value      string
	Enabled    bool
	ValidUntil sql.NullTime
	FeedID     int32
}

type User struct {
	ID           int32
	Name         string
	Email        string
	PasswordHash string
}

type UserGroup struct {
	UserID  int32
	GroupID int32
}

type UserPermission struct {
	UserID       int32
	PermissionID int32
}
