// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/feed-me/types"
)

type FeedsType string

const (
	FeedsTypeIp     FeedsType = "ip"
	FeedsTypeDomain FeedsType = "domain"
	FeedsTypeUrl    FeedsType = "url"
)

func (e *FeedsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FeedsType(s)
	case string:
		*e = FeedsType(s)
	default:
		return fmt.Errorf("unsupported scan type for FeedsType: %T", src)
	}
	return nil
}

type NullFeedsType struct {
	FeedsType FeedsType `json:"feeds_type"`
	Valid     bool      `json:"valid"` // Valid is true if FeedsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFeedsType) Scan(value interface{}) error {
	if value == nil {
		ns.FeedsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FeedsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFeedsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FeedsType), nil
}

func (e FeedsType) Valid() bool {
	switch e {
	case FeedsTypeIp,
		FeedsTypeDomain,
		FeedsTypeUrl:
		return true
	}
	return false
}

type DomainEntry struct {
	ID          int64          `json:"id"`
	Value       string         `json:"value"`
	Enabled     bool           `json:"enabled"`
	Description sql.NullString `json:"description"`
	ValidUntil  sql.NullTime   `json:"valid_until"`
	FeedID      int32          `json:"feed_id"`
}

type Feed struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsPublic    bool           `json:"is_public"`
	Type        FeedsType      `json:"type"`
}

type IpEntry struct {
	ID          int64          `json:"id"`
	Value       types.MyNet    `json:"value"`
	Enabled     bool           `json:"enabled"`
	Description sql.NullString `json:"description"`
	ValidUntil  sql.NullTime   `json:"valid_until"`
	FeedID      int32          `json:"feed_id"`
}

type UrlEntry struct {
	ID          int64          `json:"id"`
	Value       string         `json:"value"`
	Enabled     bool           `json:"enabled"`
	Description sql.NullString `json:"description"`
	ValidUntil  sql.NullTime   `json:"valid_until"`
	FeedID      int32          `json:"feed_id"`
}

type User struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}
