// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/feed-me/types"
	"github.com/jackc/pgx/v5/pgtype"
)

type Feedtype string

const (
	FeedtypeIp     Feedtype = "ip"
	FeedtypeDomain Feedtype = "domain"
	FeedtypeUrl    Feedtype = "url"
)

func (e *Feedtype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Feedtype(s)
	case string:
		*e = Feedtype(s)
	default:
		return fmt.Errorf("unsupported scan type for Feedtype: %T", src)
	}
	return nil
}

type NullFeedtype struct {
	Feedtype Feedtype `json:"feedtype"`
	Valid    bool     `json:"valid"` // Valid is true if Feedtype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFeedtype) Scan(value interface{}) error {
	if value == nil {
		ns.Feedtype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Feedtype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFeedtype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Feedtype), nil
}

func (e Feedtype) Valid() bool {
	switch e {
	case FeedtypeIp,
		FeedtypeDomain,
		FeedtypeUrl:
		return true
	}
	return false
}

type DomainEntry struct {
	ID          int64            `json:"id"`
	Value       string           `json:"value"`
	Enabled     bool             `json:"enabled"`
	Description *string          `json:"description"`
	ValidUntil  pgtype.Timestamp `json:"valid_until"`
	FeedID      int64            `json:"feed_id"`
}

type Feed struct {
	ID          int64    `json:"id"`
	Name        string   `json:"name"`
	Description *string  `json:"description"`
	IsPublic    bool     `json:"is_public"`
	Type        Feedtype `json:"type"`
}

type IpEntry struct {
	ID          int64            `json:"id"`
	Value       types.MyNet      `json:"value"`
	Enabled     bool             `json:"enabled"`
	Description *string          `json:"description"`
	ValidUntil  pgtype.Timestamp `json:"valid_until"`
	FeedID      int64            `json:"feed_id"`
}

type UrlEntry struct {
	ID          int64            `json:"id"`
	Value       string           `json:"value"`
	Enabled     bool             `json:"enabled"`
	Description *string          `json:"description"`
	ValidUntil  pgtype.Timestamp `json:"valid_until"`
	FeedID      int64            `json:"feed_id"`
}

type User struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}
